# Tutorial 1 {#sec:T1}

## Q1

- Moment-generating function $M(t)$ of a random variable $X$ defined in $D$ that has a density function $f(x)$. 
\begin{align}
M(t) = \mathbb{E}(e^{tx}) &= \int_{D} e^{tx}f(x)dx\\
\mathbb{E}(X^{s}) &= M^{(s)}(0)
\end{align}

- Relationship between $\bar X=\frac{1}{n}\sum\limits_{i=1}^n X_i$ and $S^2=\frac{1}{n-1}\sum\limits_{i=1}^n(X_i-\bar X)^2$, independent.

- How to derive a quantity following $t$ distribution from a norm population.
\begin{align}
T=\frac{\frac{\bar{X}-\mu}{\sigma / \sqrt{n}}}{\sqrt{\frac{(n-1) S^{2}}{\sigma^{2}} /(n-1)}}=\frac{\bar{X}-\mu}{S / \sqrt{n}}
\end{align}

- The $t$ distribution is symmetric, i.e., $t_{q}(n) = -t_{1-q}(n), q\in(0,1)$. For example, 
```{r sym_t}
qt(0.025, 8, lower.tail = F)
-qt(1 - 0.025, 8, lower.tail = F)
```

- Properties of $F$ distribution.

## Q2

- Standardize a norm distribution $X\in\mathcal{N}(\mu,\sigma^2)$, i.e., $\frac{X-\mu}{\sigma}\in\mathcal{N}(0,1)$.

- The distribution of $\bar X$ and $S^2$. 

## Q3

- Central Limit Theorem(CLT) 

```{theorem, clt}
**(Central Limit Theorem)** Let $X_1,\ldots,X_n$ be independent, identically
distributed (i.i.d.) random variables with finite expectation $\mu$, and
positive, finite variance $\sigma^2$, and set $S_n=X_1 + X_2 + \cdots + X_n$, $n
\ge 1$. Then
$$
    \frac{\bar{S}_n - n\mu}{\sigma \sqrt{n}}\xrightarrow{L} N(0, 1)
    ~\mathrm{as}~n\rightarrow\infty.
$$
```

- The relationship between Binimial distribution and Poisson distribution

- Aware the power of CLT.