# Confidence Interval

```{definition, name = "Confidence Interval"}
Given a sample $X_1,X_2,...,X_n$ of the population $X\sim f(x;\theta)$ and $\alpha\in[0,1]$, a $(1-\alpha)$ confidence interval $\left(a(X_1,X_2,...,X_n), b(X_1,X_2,...,X_n)\right)$ for the parameter $\theta$ is defined such that, 
\begin{equation}
P\left[a(X_1,X_2,...,X_n)< \theta <b(X_1,X_2,...,X_n)\right] = 1-\alpha
\end{equation}
```


**[Interpretation and misunderstanding](https://en.wikipedia.org/wiki/Confidence_interval#Meaning_and_interpretation)**

## Q1 

```{definition, name = "t-distribution"}
Suppose $X\sim N(0, 1)$, $U\sim \chi^2(n)$, and $X$ are independent from $Y$, then 
$\frac{X}{\sqrt{U/n}}$ has a (student) t distribution with n degrees of freedom, i.e., 
$$
  \frac{X}{\sqrt{U/n}} \sim t(n)
$$
  
```

Confidence Interval of normal population $X_i\stackrel{i.i.d.}\sim \mathcal{N}(\mu,\sigma^2),i=1,2,...,n$. We have 
\begin{align}
\bar X \sim \mathcal{N}(\mu,\frac{\sigma^2}{n}), \quad \frac{(n-1)S^2}{\sigma^2}\sim \chi^2(n-1)
\end{align}
It can be proved that $\bar X$ and $S^2$ are independent. Then, 
\begin{equation}
\frac{\frac{\bar X - \mu}{\sqrt{\sigma^2/n}}}{\sqrt{\frac{(n-1)S^2}{\sigma^2} / (n-1)}} = \frac{\bar X -\mu}{S/\sqrt{n}}\sim t(n-1)
(#eq:tn)
\end{equation}
We call such a method the pivotal approach. A pivotal quantity or pivot is a function of observations and unobservable parameters such that the function's probability distribution does not depend on the unknown parameters. For example, $\frac{\bar X - \mu}{\sqrt{\sigma^2/n}}\sim \mathcal{N}(0,1)$ is a pivot. From \@ref(eq:tn), we derive the $(1-\alpha)$ confidence interval for the mean $\mu$ when $\sigma^2$ is unknown, i.e., 
\begin{equation}
\bar X \pm t_{\alpha/2}(n-1)\frac{S}{\sqrt{n}}
\end{equation}

```{r}
x <- c(21.5, 18.95, 18.55, 19.4, 19.15, 22.35, 22.9, 22.2, 23.1)
t.test(x, conf.level = 0.95)
```

## Q2 

```{theorem, name = "Welch’s t-interval"}
Let $X_1,X_2,...,X_n\stackrel{i.i.d.}{\sim}\mathcal{N}(\mu_X,\sigma^2_X)$ and $Y_1,Y_2,...,Y_m\stackrel{i.i.d.}{\sim}\mathcal{N}(\mu_Y,\sigma^2_Y)$ be independent random variables. Then an approximate $(1-\alpha)$ C.I. for $\mu_X-\mu_Y$ is 
$$
  \bar{X}-\bar{Y} \pm t_{\alpha / 2}(r) \sqrt{\frac{S_{X}^{2}}{n}+\frac{S_{Y}^{2}}{m}}
$$
where
$$
  r=\left\lfloor\frac{\left(\frac{S_{\mathrm{X}}^{2}}{n}+\frac{S_{\mathrm{X}}^{2}}{m}\right)^{2}}{\frac{1}{n-1}\left(\frac{S_{\mathrm{X}}^{2}}{n}\right)^{2}+\frac{1}{m-1}\left(\frac{S_{\mathrm{Y}}^{2}}{m}\right)^{2}}\right\rfloor
$$
```

Let $X_1,X_2,...,X_n\stackrel{i.i.d.}{\sim}\mathcal{N}(\mu_X,\sigma^2_X)$ and $Y_1,Y_2,...,Y_m\stackrel{i.i.d.}{\sim}\mathcal{N}(\mu_Y,\sigma^2_Y)$ be independent random variables. We have the following, 
\begin{align}
\bar X&\sim \mathcal{N}(\mu_X, \frac{\sigma_X^2}{n}), \quad 
\bar Y \sim \mathcal{N}(\mu_Y, \frac{\sigma_Y^2}{n})\\
\frac{(n-1)S^2_X}{\sigma_X^2} &\sim \chi^2(n-1), \quad \frac{(m-1)S^2_Y}{\sigma_Y^2} \sim \chi^2(m-1)
\end{align}
The two samples are independent, hence, 
\begin{equation}
\bar X - \bar Y \sim \mathcal{N}(\mu_X-\mu_Y,\frac{\sigma_X^2}{n}+\frac{\sigma_Y^2}{m})
\end{equation}

* $\sigma_X=\sigma_Y=\sigma$ and $\sigma$ is known, then, 
\begin{equation}
\frac{\bar X - \bar Y - (\mu_X-\mu_Y)}{\sqrt{\frac{\sigma^2}{n}+\frac{\sigma^2}{m}}}\sim \mathcal{N}(0,1)
\end{equation}

* $\sigma_X=\sigma_Y=\sigma$ and $\sigma$ is unknown, then, 
\begin{align}
\frac{(n-1)S_X^2+(m-1)S_Y^2}{\sigma^2}&\sim \chi^2(n+m-2)\\
\frac{\bar X - \bar Y-(\mu_X-\mu_Y)/\left(\sqrt{\frac{\sigma^2}{n}+\frac{\sigma^2}{m}}\right)}{\sqrt{\frac{(n-1)S_X^2+(m-1)S_Y^2}{\sigma^2(n+m-2)}}}&\sim t(n+m-2)
\end{align}

* $\sigma_X\neq\sigma_Y$ and they are both unknown, use Welch’s t-interval or CLT approximation.

* $m=n$, then $Z_i = X_i-Y_i\sim\mathcal{N}(\mu_X-\mu_y,\sigma_Z)$ since $(X_i,Y_i)^T\sim \mathcal{N}\left((\mu_X,\mu_Y)^T, \Sigma\right)$. Then the same technique in Q1 can be used.

## Q3

If $X\sim \chi^2(n)$ and $Y\sim\chi^2(m)$ are independent, then 
$$
\frac{X/n}{Y/m}\sim F(n, m)
$$
Therefore, with samples from two independent normal population, i.e., let $X_1,X_2,...,X_n\stackrel{i.i.d.}{\sim}\mathcal{N}(\mu_X,\sigma^2_X)$ and $Y_1,Y_2,...,Y_m\stackrel{i.i.d.}{\sim}\mathcal{N}(\mu_Y,\sigma^2_Y)$ be independent, we have a pivot 
\begin{equation}
\frac{\frac{(n-1)S_X^2}{\sigma^2_X} / (n-1)}{\frac{(m-1)S_Y^2}{\sigma^2_Y}/(m-1)} = \frac{S_X^2/\sigma^2_X}{S_Y^2/\sigma^2_Y}\sim F(n-1, m-1)
\end{equation}

## Q4

According to the central limit theorem(CLT), we have an approximate pivot 
\begin{equation}
\frac{\bar X - EX}{\sqrt{Var X}}\rightarrow \mathcal{N}(0,1)
\end{equation}


